site_name: Electronics Pocketbook

repo_url: https://github.com/YePererva/electronics_pocketbook

docs_dir: docs/content
custom_dir: overrides

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono

